name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
env:
  BIN_NAME: silk-cli

jobs:
  compile:
    name: Compile
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            rid: linux-x64
            postfix: ""

          # Windows
          - os: ubuntu-latest
            target: x86_64-pc-windows-gnu
            rid: win-x64
            postfix: ".exe"

          # Mac OSX
          - os: macos-latest
            target: x86_64-apple-darwin
            rid: osx-x64
            postfix: ""

          - os: macos-latest
            target: aarch64-apple-darwin
            rid: osx-arm64
            postfix: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Tag
        id: tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "version=${GITHUB_REF##refs/tags/}" >> $GITHUB_OUTPUT

      - name: Resume cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ matrix.target }}-release-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ matrix.target }}-release
      
      - name: Install Dependencies (Ubuntu only)
        if: startsWith(matrix.os, 'ubuntu-') 
        run: | 
          sudo apt update
          sudo apt install -y mingw-w64 mingw-w64-tools mingw-w64-x86-64-dev musl-tools

      - name: Build executable
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --release --target ${{ matrix.target }}

      - name: Rename binary
        run: |
          mv target/${{ matrix.target }}/release/${{ env.BIN_NAME }}${{ matrix.postfix }} ${{ env.BIN_NAME }}${{ matrix.postfix }}
          zip -r ${{ env.BIN_NAME }}-${{ matrix.rid }}-${{ steps.tag.outputs.version }}.zip ${{ env.BIN_NAME }}${{ matrix.postfix }}

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: compile-${{ matrix.target }}
          path: ${{ env.BIN_NAME }}-${{ matrix.rid }}-${{ steps.tag.outputs.version }}.zip

  release:
    name: Release
    needs: [compile]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Prepare Tag
        id: tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "version=${GITHUB_REF##refs/tags/}" >> $GITHUB_OUTPUT

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          pattern: compile-*
          merge-multiple: true
          path: ./packages

      - name: Github release
        uses: "softprops/action-gh-release@v1"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          files: |
            ./packages/${{ env.BIN_NAME }}-linux-x64-${{ steps.tag.outputs.version }}.zip
            ./packages/${{ env.BIN_NAME }}-win-x64-${{ steps.tag.outputs.version }}.zip
            ./packages/${{ env.BIN_NAME }}-osx-x64-${{ steps.tag.outputs.version }}.zip
            ./packages/${{ env.BIN_NAME }}-osx-arm64-${{ steps.tag.outputs.version }}.zip